apiVersion: v1 
kind: Service
metadata:
  name: svc-clientside
  namespace: dev
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32031 
  selector:
    app: clientside