apiVersion: v1
kind: Service
metadata:
  name: srv-sqlserver
  namespace: dev
spec:
  type: ClusterIP  
  ports:
    - port: 1433              
      targetPort: 1433        
  selector:
    app: sqlserver            
